"""
OPTIMUS — Complete Kernel
=========================

Architecture:
    FreeCat(Graph) --F--> RuntimeCat_Q --Optimus--> RuntimeCat_Q

Three-layer system:
    1. FreeCategory        — syntax, paths as lists, composition = concatenation
    2. RuntimeCategory     — enriched over a quantale, morphisms carry confidence
    3. OptimisMonad        — endofunctor + monad structure + factorization search

The gradient:
    Classical:  x_{t+1} = x_t - η∇L(x_t)
    Optimus:    m_{t+1} = argmax_{f in factorizations(m_t)} w(f)

    Instead of adjusting parameters, Optimus discovers intermediate objects.
    The "gradient direction" is the set of all factorizations A→B→C of a morphism A→C.
    Better factorizations = higher confidence paths = uphill in the quantale order.

Monad structure:
    unit     : m → Optimus(m)              lift (identity action)
    multiply : Optimus²(m) → Optimus(m)   collapse nested search (prevent explosion)
    bind     : m → (m → Optimus(n)) → Optimus(n)   chain refinements

Tarski stability:
    Every rewrite must satisfy w(new) >= w(old) in the quantale order.
    This guarantees monotone convergence to a fixpoint.

Yoneda:
    Every object X is represented by its relational fingerprint:
        hom_in(X)  = {f : A → X for all A}
        hom_out(X) = {f : X → B for all B}
    Two objects with identical fingerprints are categorically indistinguishable.
    Replication = reconstruct from fingerprint.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Callable, Optional, Iterator
from itertools import product as iproduct
import math
import time


# ══════════════════════════════════════════════════════════════════════════════
# QUANTALE
# ══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class Quantale:
    """
    A complete lattice with an associative tensor product and unit.
    Determines how confidence scores compose and what 'better' means.
    """
    name: str
    tensor:  Callable[[float, float], float]
    unit:    float
    leq:     Callable[[float, float], bool]   # a <= b in the quantale order

    def compose(self, a: float, b: float) -> float:
        return self.tensor(a, b)

    def compose_path(self, weights: list[float]) -> float:
        result = self.unit
        for w in weights:
            result = self.tensor(result, w)
        return result

    def better(self, new: float, old: float) -> bool:
        """Is new strictly better than old?"""
        return self.leq(old, new) and not math.isclose(new, old, rel_tol=1e-9)

    def at_least_as_good(self, new: float, old: float) -> bool:
        """Tarski condition: new >= old."""
        return self.leq(old, new)

    def loss(self, w: float) -> float:
        """Treat weight as negative log-loss for display purposes."""
        if w <= 0:
            return float('inf')
        return -math.log(w)


MULTIPLICATIVE = Quantale(
    name="multiplicative",
    tensor=lambda a, b: a * b,
    unit=1.0,
    leq=lambda a, b: a <= b         # higher confidence = better
)

ADDITIVE = Quantale(
    name="additive",
    tensor=lambda a, b: a + b,
    unit=0.0,
    leq=lambda a, b: a >= b         # lower cost = better
)

MIN_QUANTALE = Quantale(
    name="min",
    tensor=min,
    unit=1.0,
    leq=lambda a, b: a <= b         # bottleneck: best = highest minimum link
)


# ══════════════════════════════════════════════════════════════════════════════
# FREE CATEGORY  (Syntax Layer)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class Path:
    """
    A morphism in the free category.
    Stored as a list of edge names — composition is concatenation.
    Identity morphism = empty list.
    Category laws (associativity, identity) are automatic.
    """
    source: str
    target: str
    edges:  list[str] = field(default_factory=list)

    @property
    def is_identity(self) -> bool:
        return len(self.edges) == 0

    @property
    def length(self) -> int:
        return len(self.edges)

    def __repr__(self):
        if self.is_identity:
            return f"id({self.source})"
        chain = " ∘ ".join(reversed(self.edges))
        return f"[{chain}] : {self.source} → {self.target}"

    def __hash__(self):
        return hash((self.source, self.target, tuple(self.edges)))

    def __eq__(self, other):
        return (self.source == other.source and
                self.target == other.target and
                self.edges == other.edges)


class FreeCategory:
    """
    FreeCat(Graph): the free category generated by a directed graph.

    Objects   = nodes
    Morphisms = finite paths (lists of edges)
    Composition = list concatenation
    Identity  = empty path

    This is the syntax layer. No semantics, no enrichment — pure structure.
    """

    def __init__(self, name: str = "SyntaxCat"):
        self.name = name
        self.objects: set[str] = set()
        self.edges: dict[str, tuple[str, str]] = {}   # name → (src, tgt)

    def add_object(self, name: str) -> str:
        self.objects.add(name)
        return name

    def add_objects(self, *names: str) -> list[str]:
        for n in names:
            self.add_object(n)
        return list(names)

    def add_edge(self, name: str, src: str, tgt: str) -> Path:
        assert src in self.objects, f"Unknown source object: {src}"
        assert tgt in self.objects, f"Unknown target object: {tgt}"
        self.edges[name] = (src, tgt)
        return Path(src, tgt, [name])

    def identity(self, obj: str) -> Path:
        assert obj in self.objects, f"Unknown object: {obj}"
        return Path(obj, obj, [])

    def compose(self, f: Path, g: Path) -> Path:
        """g after f.  Requires f.target == g.source."""
        if f.target != g.source:
            raise ValueError(
                f"Not composable: {f} has target {f.target}, "
                f"{g} has source {g.source}"
            )
        return Path(f.source, g.target, f.edges + g.edges)

    def compose_many(self, paths: list[Path]) -> Path:
        """Compose a sequence of paths left-to-right (f₁ then f₂ then ...)."""
        assert paths, "Cannot compose empty sequence"
        result = paths[0]
        for p in paths[1:]:
            result = self.compose(result, p)
        return result

    def all_paths(self, src: str, tgt: str,
                  max_length: int = 6) -> Iterator[Path]:
        """BFS over all paths from src to tgt up to max_length."""
        from collections import deque
        queue = deque([Path(src, src, [])])
        while queue:
            current = queue.popleft()
            if current.target == tgt and current.length > 0:
                yield current
            if current.length >= max_length:
                continue
            for edge_name, (esrc, etgt) in self.edges.items():
                if esrc == current.target:
                    queue.append(Path(current.source, etgt,
                                      current.edges + [edge_name]))

    def parse(self, expr: str) -> Path:
        """
        Mini text syntax:
            'f'           → single edge morphism
            'g ∘ f'       → compose: f first, then g  (standard math notation)
            'f ; g'       → compose: f first, then g  (diagrammatic order)
        """
        if '∘' in expr:
            parts = [p.strip() for p in expr.split('∘')]
            parts = list(reversed(parts))      # math notation: right to left
        elif ';' in expr:
            parts = [p.strip() for p in expr.split(';')]
        else:
            parts = [expr.strip()]

        paths = []
        for name in parts:
            src, tgt = self.edges[name]
            paths.append(Path(src, tgt, [name]))
        return self.compose_many(paths)


# ══════════════════════════════════════════════════════════════════════════════
# ENRICHED MORPHISM  (Runtime value)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class EnrichedMorphism:
    """
    A morphism in the enriched runtime category.
    Carries: identity, type, confidence score, optional implementation,
             provenance chain, and generation counter.
    """
    name:        str
    source:      str
    target:      str
    confidence:  float = 1.0
    fn:          Optional[Callable] = None
    provenance:  list[str] = field(default_factory=list)
    generation:  int = 0          # how many refinement steps produced this
    metadata:    dict = field(default_factory=dict)

    def __call__(self, x):
        if self.fn is None:
            raise ValueError(f"Morphism '{self.name}' has no implementation")
        return self.fn(x)

    def loss(self, q: Quantale) -> float:
        return q.loss(self.confidence)

    def __repr__(self):
        gen = f" gen={self.generation}" if self.generation > 0 else ""
        return (f"{self.name} : {self.source} → {self.target} "
                f"[conf={self.confidence:.4f}{gen}]")

    def __hash__(self):
        return hash((self.source, self.target, self.name))

    def __eq__(self, other):
        return self.name == other.name


# ══════════════════════════════════════════════════════════════════════════════
# ENRICHED RUNTIME CATEGORY
# ══════════════════════════════════════════════════════════════════════════════

class RuntimeCategory:
    """
    The enriched runtime category.

    Every morphism carries a quantale-valued weight.
    Composition propagates weights via the quantale tensor.
    Maintains the complete morphism graph for factorization search.
    """

    def __init__(self, name: str = "RuntimeCat",
                 quantale: Quantale = MULTIPLICATIVE):
        self.name = name
        self.quantale = quantale
        self.objects:   dict[str, dict] = {}
        self.morphisms: dict[str, EnrichedMorphism] = {}
        self._history:  list[dict] = []           # audit trail

    # ── Objects ──────────────────────────────────────────────────

    def add_object(self, name: str, **attrs) -> str:
        self.objects[name] = attrs
        return name

    def add_objects(self, *names: str) -> list[str]:
        for n in names:
            self.add_object(n)
        return list(names)

    def get_or_create_object(self, name: str) -> str:
        if name not in self.objects:
            self.add_object(name)
        return name

    # ── Morphisms ─────────────────────────────────────────────────

    def add_morphism(self, name: str, src: str, tgt: str,
                     confidence: float = 1.0,
                     fn: Optional[Callable] = None,
                     **metadata) -> EnrichedMorphism:
        self.get_or_create_object(src)
        self.get_or_create_object(tgt)
        m = EnrichedMorphism(name, src, tgt, confidence, fn,
                             provenance=[name], metadata=metadata)
        self.morphisms[name] = m
        self._history.append({"op": "add", "morphism": name,
                               "confidence": confidence})
        return m

    def identity(self, obj: str) -> EnrichedMorphism:
        name = f"id({obj})"
        if name in self.morphisms:
            return self.morphisms[name]
        m = EnrichedMorphism(name, obj, obj, self.quantale.unit,
                             fn=lambda x: x, provenance=[])
        self.morphisms[name] = m
        return m

    def compose(self, f: EnrichedMorphism,
                g: EnrichedMorphism,
                name: Optional[str] = None,
                store: bool = True) -> EnrichedMorphism:
        """
        Compose f then g.
        confidence(g∘f) = quantale.tensor(f.confidence, g.confidence)
        """
        if f.target != g.source:
            raise ValueError(
                f"Not composable: {f.name}.target={f.target} ≠ "
                f"{g.name}.source={g.source}"
            )
        confidence = self.quantale.compose(f.confidence, g.confidence)
        composed_fn = None
        if f.fn and g.fn:
            composed_fn = lambda x, _f=f.fn, _g=g.fn: _g(_f(x))
        name = name or f"{g.name}∘{f.name}"
        generation = max(f.generation, g.generation)
        m = EnrichedMorphism(
            name, f.source, g.target, confidence, composed_fn,
            f.provenance + g.provenance, generation
        )
        if store:
            self.morphisms[name] = m
            self._history.append({"op": "compose", "morphism": name,
                                   "confidence": confidence})
        return m

    def compose_path(self, morphisms: list[EnrichedMorphism],
                     name: Optional[str] = None) -> EnrichedMorphism:
        """Compose a sequence of morphisms left-to-right."""
        assert morphisms, "Empty path"
        result = morphisms[0]
        for m in morphisms[1:]:
            result = self.compose(result, m, store=False)
        if name:
            result.name = name
        self.morphisms[result.name] = result
        return result

    # ── Graph queries ─────────────────────────────────────────────

    def morphisms_from(self, src: str) -> list[EnrichedMorphism]:
        return [m for m in self.morphisms.values() if m.source == src]

    def morphisms_to(self, tgt: str) -> list[EnrichedMorphism]:
        return [m for m in self.morphisms.values() if m.target == tgt]

    def morphisms_between(self, src: str,
                          tgt: str) -> list[EnrichedMorphism]:
        return [m for m in self.morphisms.values()
                if m.source == src and m.target == tgt]

    def best_morphism(self, src: str,
                      tgt: str) -> Optional[EnrichedMorphism]:
        candidates = self.morphisms_between(src, tgt)
        if not candidates:
            return None
        return max(candidates, key=lambda m: m.confidence
                   if self.quantale.name == "multiplicative" else -m.confidence)

    # ── Yoneda representation ──────────────────────────────────────

    def yoneda_in(self, obj: str) -> dict[str, EnrichedMorphism]:
        """Hom(-, obj): all morphisms into obj. The contravariant Yoneda."""
        return {m.name: m for m in self.morphisms_to(obj)}

    def yoneda_out(self, obj: str) -> dict[str, EnrichedMorphism]:
        """Hom(obj, -): all morphisms out of obj. The covariant Yoneda."""
        return {m.name: m for m in self.morphisms_from(obj)}

    def yoneda_fingerprint(self, obj: str) -> dict:
        """
        Full relational fingerprint of an object.
        Two objects with identical fingerprints are isomorphic.
        """
        return {
            "object": obj,
            "hom_in":  {k: v.confidence for k, v in self.yoneda_in(obj).items()},
            "hom_out": {k: v.confidence for k, v in self.yoneda_out(obj).items()},
        }

    def yoneda_similarity(self, a: str, b: str) -> float:
        """
        Cosine-like similarity between two objects' Yoneda fingerprints.
        1.0 = structurally identical, 0.0 = no shared relationships.
        """
        fp_a = self.yoneda_fingerprint(a)
        fp_b = self.yoneda_fingerprint(b)

        all_keys = (set(fp_a["hom_in"]) | set(fp_b["hom_in"]) |
                    set(fp_a["hom_out"]) | set(fp_b["hom_out"]))

        if not all_keys:
            return 1.0 if a == b else 0.0

        shared = sum(
            min(fp_a["hom_in"].get(k, 0), fp_b["hom_in"].get(k, 0)) +
            min(fp_a["hom_out"].get(k, 0), fp_b["hom_out"].get(k, 0))
            for k in all_keys
        )
        total = sum(
            max(fp_a["hom_in"].get(k, 0), fp_b["hom_in"].get(k, 0)) +
            max(fp_a["hom_out"].get(k, 0), fp_b["hom_out"].get(k, 0))
            for k in all_keys
        )
        return shared / total if total > 0 else 0.0

    def stats(self) -> dict:
        return {
            "objects": len(self.objects),
            "morphisms": len(self.morphisms),
            "rewrites": sum(1 for h in self._history if h["op"] == "rewrite"),
        }


# ══════════════════════════════════════════════════════════════════════════════
# FUNCTOR  (Interpreter)
# ══════════════════════════════════════════════════════════════════════════════

class Functor:
    """
    F : FreeCat(Graph) → RuntimeCat

    The interpreter. Maps syntax to enriched runtime morphisms.
    Functor law: F(g ∘ f) = F(g) ∘ F(f)
    This is enforced structurally: interpreting a path = composing its edges.
    """

    def __init__(self, syntax: FreeCategory, runtime: RuntimeCategory,
                 name: str = "F"):
        self.name = name
        self.syntax = syntax
        self.runtime = runtime
        self._object_map:    dict[str, str] = {}
        self._edge_map:      dict[str, EnrichedMorphism] = {}

    def map_object(self, syn_obj: str,
                   run_obj: Optional[str] = None) -> str:
        run_obj = run_obj or syn_obj
        self.runtime.get_or_create_object(run_obj)
        self._object_map[syn_obj] = run_obj
        return run_obj

    def map_edge(self, edge_name: str,
                 morphism: EnrichedMorphism) -> EnrichedMorphism:
        self._edge_map[edge_name] = morphism
        return morphism

    def interpret(self, path: Path) -> EnrichedMorphism:
        """
        Interpret a free-category path as an enriched runtime morphism.
        F(g ∘ f) = F(g) ∘ F(f)  — functor law holds by construction.
        """
        if path.is_identity:
            obj = self._object_map.get(path.source, path.source)
            return self.runtime.identity(obj)

        morphisms = []
        for edge in path.edges:
            m = self._edge_map.get(edge)
            if m is None:
                raise KeyError(
                    f"Functor {self.name}: no mapping for edge '{edge}'"
                )
            morphisms.append(m)

        return self.runtime.compose_path(morphisms)

    def verify_functor_law(self, f_name: str, g_name: str) -> bool:
        """
        Check F(g ∘ f) == F(g) ∘ F(f) for named edges f, g.
        Returns True if functor law holds.
        """
        syn = self.syntax
        f_path = Path(*syn.edges[f_name], [f_name])
        g_path = Path(*syn.edges[g_name], [g_name])

        if f_path.target != g_path.source:
            return True    # not composable, vacuously true

        composed_path = syn.compose(f_path, g_path)

        F_gof = self.interpret(composed_path)
        F_f   = self.interpret(f_path)
        F_g   = self.interpret(g_path)
        F_g_after_F_f = self.runtime.compose(F_f, F_g, store=False)

        return (F_gof.source == F_g_after_F_f.source and
                F_gof.target == F_g_after_F_f.target and
                math.isclose(F_gof.confidence,
                             F_g_after_F_f.confidence, rel_tol=1e-9))


# ══════════════════════════════════════════════════════════════════════════════
# OPTIMUS MONAD  (The Refinement Engine)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class Rewrite:
    """A single rewrite event produced by the Optimus monad."""
    kind:               str              # 'compress' | 'factorize' | 'absorb'
    old_morphisms:      list[str]
    new_morphism:       str
    confidence_before:  list[float]
    confidence_after:   float
    generation:         int
    timestamp:          float = field(default_factory=time.time)

    def improvement(self, q: Quantale) -> float:
        """How much better is the new morphism vs the composed old path?"""
        old_conf = q.compose_path(self.confidence_before)
        return self.confidence_after - old_conf

    def __repr__(self):
        before = " ⊗ ".join(f"{c:.3f}" for c in self.confidence_before)
        arrow = " → ".join(self.old_morphisms)
        return (f"[gen={self.generation}] {arrow} "
                f"⟶ {self.new_morphism}  "
                f"[{before} = {self.confidence_after:.4f}]")


class OptimisMonad:
    """
    Optimus : Monad on RuntimeCat

    The refinement engine. Searches for better factorizations of morphisms.

    Monad structure:
        unit     : m → {m}                    lift, no change
        multiply : {{m}} → {m}                collapse nested search
        bind     : m → (m → {n}) → {n}        chain refinements

    The categorical gradient:
        Given m : A → C, search all objects B such that A→B and B→C exist.
        Score each factorization A→B→C by w(A→B) ⊗ w(B→C).
        Return the best factorization if it beats the current morphism.
        This is hill-climbing in morphism space.

    Tarski stability:
        Every accepted rewrite satisfies w(new) >= w(old).
        The system is monotone and converges to a fixpoint.
    """

    def __init__(self, runtime: RuntimeCategory, max_depth: int = 3):
        self.runtime   = runtime
        self.max_depth = max_depth
        self.rewrites:  list[Rewrite] = []
        self.generation = 0

    # ── Monad unit ────────────────────────────────────────────────

    def unit(self, m: EnrichedMorphism) -> list[EnrichedMorphism]:
        """Lift a morphism into the monad. Identity action."""
        return [m]

    # ── Monad multiply ────────────────────────────────────────────

    def multiply(self, candidates: list[list[EnrichedMorphism]]
                 ) -> list[EnrichedMorphism]:
        """
        Monad multiplication: collapse nested candidate sets.
        Optimus²(m) → Optimus(m)
        Prevents exponential explosion of nested search.
        """
        flat = {}
        for group in candidates:
            for m in group:
                key = (m.source, m.target)
                existing = flat.get(key)
                if existing is None or self.runtime.quantale.better(
                        m.confidence, existing.confidence):
                    flat[key] = m
        return list(flat.values())

    # ── Monad bind ────────────────────────────────────────────────

    def bind(self, m: EnrichedMorphism,
             f: Callable[[EnrichedMorphism],
                         list[EnrichedMorphism]]) -> list[EnrichedMorphism]:
        """Chain refinements: m >>= f"""
        return self.multiply([f(n) for n in self.unit(m)])

    # ── Factorization search  (the categorical gradient) ──────────

    def factorizations(self, m: EnrichedMorphism,
                       depth: int = 1) -> list[list[EnrichedMorphism]]:
        """
        Find all factorizations of m : A → C.

        depth=1: single intermediate  A → B → C
        depth=2: two intermediates    A → B → D → C
        etc.

        Returns a list of paths (each path = list of morphisms).
        Only returns paths with strictly better confidence than m.
        """
        q = self.runtime.quantale
        results = []
        self._factorize_rec(
            m.source, m.target, [], m.confidence, depth, results
        )
        return results

    def _factorize_rec(self, current: str, target: str,
                       path_so_far: list[EnrichedMorphism],
                       threshold: float,
                       depth: int,
                       results: list) -> None:
        """
        DFS over factorizations.
        depth = additional intermediates allowed.
        At each node: try completing to target, then recurse deeper.
        """
        q = self.runtime.quantale

        # Try to complete the path directly to target (requires >=1 edge already)
        if len(path_so_far) > 0:
            for m in self.runtime.morphisms_from(current):
                if m.target == target:
                    full_path = path_so_far + [m]
                    conf = q.compose_path([x.confidence for x in full_path])
                    if q.better(conf, threshold):
                        results.append(full_path)

        if depth == 0:
            return

        # Explore further intermediates
        for m in self.runtime.morphisms_from(current):
            if m.target == target:
                continue  # already handled above
            self._factorize_rec(
                m.target, target,
                path_so_far + [m],
                threshold, depth - 1, results
            )

    # ── Compression  (materialize a path as a single morphism) ────

    def compress(self, path: list[EnrichedMorphism],
                 name: Optional[str] = None) -> Optional[EnrichedMorphism]:
        """
        Materialize a multi-hop path as a single shortcut morphism.
        Only accepted if it improves over any existing A→Z morphism.
        Tarski condition: new confidence >= existing best confidence.
        """
        assert len(path) >= 2, "Need at least 2 morphisms to compress"
        q = self.runtime.quantale

        confidence = q.compose_path([m.confidence for m in path])
        existing = self.runtime.best_morphism(path[0].source, path[-1].target)

        if existing and not q.better(confidence, existing.confidence):
            return None    # no improvement — reject

        name = name or f"shortcut({path[0].source}→{path[-1].target})"
        composed_fn = None
        fns = [m.fn for m in path]
        if all(fns):
            def make_pipeline(funcs):
                def pipeline(x):
                    for f in funcs:
                        x = f(x)
                    return x
                return pipeline
            composed_fn = make_pipeline(fns)

        shortcut = EnrichedMorphism(
            name, path[0].source, path[-1].target, confidence,
            composed_fn,
            provenance=[e for m in path for e in m.provenance],
            generation=self.generation
        )
        self.runtime.morphisms[name] = shortcut

        rewrite = Rewrite(
            kind="compress",
            old_morphisms=[m.name for m in path],
            new_morphism=name,
            confidence_before=[m.confidence for m in path],
            confidence_after=confidence,
            generation=self.generation
        )
        self.rewrites.append(rewrite)
        self.runtime._history.append({"op": "rewrite", "morphism": name,
                                       "confidence": confidence})
        return shortcut

    # ── Refine a single morphism  (one gradient step) ─────────────

    def refine(self, m: EnrichedMorphism,
               depth: int = 1) -> Optional[EnrichedMorphism]:
        """
        One Optimus step on a morphism m.

        1. Generate candidate factorizations (the 'gradient direction').
        2. Score each by quantale composition.
        3. Accept the best if it improves m (Tarski condition).
        4. Materialize as a shortcut morphism.

        Returns the improved morphism, or None if no improvement found.
        """
        candidates = self.factorizations(m, depth=depth)
        if not candidates:
            return None

        q = self.runtime.quantale
        best_path = max(
            candidates,
            key=lambda path: q.compose_path([x.confidence for x in path])
        )
        best_conf = q.compose_path([x.confidence for x in best_path])

        if not q.better(best_conf, m.confidence):
            return None

        return self.compress(best_path)

    # ── Descent loop  (iterate until fixpoint) ────────────────────

    def descend(self, morphisms: Optional[list[str]] = None,
                max_steps: int = 20,
                depth: int = 1,
                verbose: bool = True) -> dict:
        """
        Categorical gradient descent loop.

        For each morphism in scope:
            1. Search for a better factorization.
            2. If found, accept it and add it to scope.
            3. Repeat until no morphism can be improved.

        Guaranteed to terminate: each step strictly improves confidence.
        The system converges to a fixpoint (Tarski theorem).

        Returns a summary of improvements made.
        """
        q = self.runtime.quantale
        scope = morphisms or list(self.runtime.morphisms.keys())
        improved = []
        steps = 0

        if verbose:
            print(f"\n── Optimus descent (max_steps={max_steps}, depth={depth})")

        for step in range(max_steps):
            self.generation = step + 1
            found = False

            # Snapshot current scope to avoid mutation during iteration
            current_morphisms = [
                self.runtime.morphisms[name]
                for name in scope
                if name in self.runtime.morphisms
            ]

            for m in current_morphisms:
                result = self.refine(m, depth=depth)
                if result:
                    if verbose:
                        print(f"  step {step+1}: {self.rewrites[-1]}")
                    scope.append(result.name)
                    improved.append(result.name)
                    found = True
                    steps += 1

            if not found:
                if verbose:
                    print(f"  Fixpoint reached after {steps} rewrites.")
                break

        return {
            "steps": steps,
            "improved": improved,
            "rewrites": self.rewrites[-steps:] if steps else [],
        }

    # ── Absorb: Yoneda-guided structural learning ──────────────────

    def absorb(self, source_obj: str, target_obj: str,
               threshold: float = 0.8) -> list[EnrichedMorphism]:
        """
        Kan-extension-inspired generalization.

        Given a bridge morphism source_obj → target_obj (or explicit similarity),
        transfer morphisms from source_obj to target_obj.

        The bridge morphism confidence acts as the similarity weight.
        This is the system discovering that two objects are structurally
        analogous and generalizing across them.
        """
        q = self.runtime.quantale

        # Use bridge morphism confidence as similarity if one exists
        bridge = None
        for m in self.runtime.morphisms_between(source_obj, target_obj):
            if bridge is None or m.confidence > bridge.confidence:
                bridge = m

        if bridge:
            sim = bridge.confidence
        else:
            sim = self.runtime.yoneda_similarity(source_obj, target_obj)

        if sim < threshold:
            return []

        transferred = []
        for m in self.runtime.morphisms_from(source_obj):
            new_name = f"kan({m.name}→{target_obj})"
            if new_name in self.runtime.morphisms:
                continue
            # Transfer with confidence scaled by similarity
            new_conf = q.compose(m.confidence, sim)
            new_m = self.runtime.add_morphism(
                new_name, target_obj, m.target,
                confidence=new_conf,
                fn=m.fn
            )
            new_m.generation = self.generation
            new_m.provenance = [f"kan:{m.name}", f"sim:{sim:.3f}"]
            transferred.append(new_m)

            rewrite = Rewrite(
                kind="absorb",
                old_morphisms=[m.name, f"sim({source_obj},{target_obj})={sim:.3f}"],
                new_morphism=new_name,
                confidence_before=[m.confidence, sim],
                confidence_after=new_conf,
                generation=self.generation
            )
            self.rewrites.append(rewrite)

        return transferred

    # ── Reports ───────────────────────────────────────────────────

    def report(self, verbose: bool = True) -> str:
        lines = [f"\n── Optimus Rewrite Log ({len(self.rewrites)} rewrites) ──"]
        by_kind: dict[str, list] = {}
        for r in self.rewrites:
            by_kind.setdefault(r.kind, []).append(r)

        for kind, rewrites in sorted(by_kind.items()):
            lines.append(f"\n  {kind.upper()} ({len(rewrites)} rewrites)")
            for r in rewrites:
                lines.append(f"    {r}")

        summary = (f"\n  Summary: {len(self.rewrites)} total rewrites | "
                   f"{len(by_kind)} kinds | "
                   f"gen={self.generation}")
        lines.append(summary)
        result = "\n".join(lines)
        if verbose:
            print(result)
        return result
