# SPDX-License-Identifier: LicenseRef-Proprietary-Commercial
# SPDX-FileCopyrightText: 2026 James Hawkins <jhawk314@gmail.com>

"""
Plugin Generator -- self-extension from operation signatures

The constructive dual of KOMPOSOS-IV's core/plugin_generator.py. KOMPOSOS
generates an Orion plugin when it detects a missing *capability*; OPERADUM
packages its own *components* (colours + operations, including ones it learned
by mining its build history) into a fresh DomainPlugin -- so the extended,
self-improved operad becomes a reusable, shippable artifact.

Two outputs:
  - materialize(operad) -> a live DomainPlugin wrapping the operad's current
    components (keeps the callables, so the plugin is executable). Use this to
    snapshot an operad that PatternMiner.auto_lift() has just extended.
  - generate_source(operad) -> readable Python source for a DomainPlugin
    subclass (callables become passthrough placeholders), for persistence.

This is the engine implementing its own architectural corrections (master spec
Phase 4): mine -> lift -> package -> reload.
"""

from __future__ import annotations
import textwrap
from typing import List

from .operad import Operad
from .types import Operation


class PluginGenerator:
    """Generates a DomainPlugin from an operad's components."""

    def materialize(self, operad: Operad, name: str = None):
        """Return a live DomainPlugin instance capturing the operad's current
        colours and operations (callables preserved)."""
        from ..domains.base import DomainPlugin

        domain_name = name or f"{operad.name}-generated"
        colour_names = [c.name for c in operad.colours()]
        ops = [self._copy_operation(o) for o in operad.operations()]
        algebra = operad.monoid

        class GeneratedDomain(DomainPlugin):
            name = domain_name

            def colours(self, _c=colour_names):
                return list(_c)

            def operations(self, _o=ops):
                return list(_o)

            def resource_algebra(self, _a=algebra):
                return _a

        return GeneratedDomain()

    @staticmethod
    def _copy_operation(op: Operation) -> Operation:
        """A detached copy of an operation (no operad backref), callable intact."""
        return Operation(
            name=op.name, inputs=list(op.inputs), output=op.output,
            cost=dict(op.cost), metadata=dict(op.metadata),
            provenance=op.provenance, _fn=op._fn,
        )

    def generate_source(self, operad: Operad, class_name: str = "GeneratedDomain",
                        domain_name: str = None) -> str:
        """Emit readable Python source for a DomainPlugin subclass that rebuilds
        the operad's structure. Callables are emitted as passthrough placeholders
        (structure is portable; behaviour is reattached on load)."""
        domain_name = domain_name or f"{operad.name}-generated"
        algebra = operad.monoid.name.split("(")[0]
        algebra_const = {
            "AdditiveCost": "ADDITIVE_COST", "MaxCapacity": "MAX_CAPACITY",
            "MultisetMaterials": "MULTISET_MATERIALS", "Tropical": "TROPICAL",
            "LinearTokens": "LINEAR_TOKENS",
        }.get(algebra, "ADDITIVE_COST")

        colour_names = [c.name for c in operad.colours()]
        op_lines: List[str] = []
        for o in operad.operations():
            op_lines.append(
                f'            Operation(name={o.name!r}, inputs={list(o.inputs)!r}, '
                f'output={o.output!r}, cost={dict(o.cost)!r}, '
                f'_fn=lambda *a, _o={o.output!r}: _o),'
            )
        ops_block = "\n".join(op_lines)

        return textwrap.dedent(f'''\
            # Auto-generated by OPERADUM PluginGenerator. Edit with care.
            from operadum.core.types import Operation
            from operadum.core.enrichment import {algebra_const}
            from operadum.domains.base import DomainPlugin


            class {class_name}(DomainPlugin):
                """Auto-generated domain capturing {len(colour_names)} colours, """ \\
                    """{len(op_lines)} operations."""
                name = {domain_name!r}

                def colours(self):
                    return {colour_names!r}

                def operations(self):
                    return [
            {ops_block}
                    ]

                def resource_algebra(self):
                    return {algebra_const}
            ''')
