# SPDX-License-Identifier: Apache-2.0 OR LicenseRef-KOMPOSOS-IV-Commercial
# Copyright (c) 2024-2026 James Ray Hawkins

"""
Plugin Generator — auto-implement missing primitives from specifications.

When the system discovers a missing primitive (via LinearIndependenceTest,
ArchitecturalAdvisor, or Dual Engine), this module generates a complete
Orion plugin skeleton that implements the missing capability.

The process:
1. Missing primitive is detected: "search→store capability is missing"
2. PluginSpec is synthesized: interface, protocol, Category operations
3. Plugin code is generated: complete Orion plugin with hooks, events, capabilities
4. Plugin is verified: satisfies the protocol, composes with existing plugins
5. Plugin is hot-loaded: registered with Orion Core

This is self-extension: the system implements its own architectural corrections.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from core.category import Category


@dataclass
class PluginSpec:
    """
    Formal specification of a missing capability.

    Generated by the system when a structural gap is detected.
    """
    name: str                              # e.g., "search_to_store"
    description: str                       # e.g., "Direct search→store capability"
    source_capability: str                 # e.g., "search"
    target_capability: str                 # e.g., "store"
    relation: str                          # e.g., "requires"
    confidence: float                      # How confident we are this is needed
    evidence: Dict[str, Any] = field(default_factory=dict)

    # Generated protocol
    provides: List[str] = field(default_factory=list)
    requires: List[str] = field(default_factory=list)
    events_consumed: List[str] = field(default_factory=list)
    events_published: List[str] = field(default_factory=list)

    # Category operations the plugin should perform
    category_operations: List[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.provides:
            self.provides = [f"{self.source_capability}_to_{self.target_capability}"]
        if not self.requires:
            self.requires = [self.source_capability]
        if not self.events_consumed:
            self.events_consumed = [f"{self.source_capability}.output"]
        if not self.events_published:
            self.events_published = [
                f"{self.source_capability}_to_{self.target_capability}.completed",
            ]
        if not self.category_operations:
            self.category_operations = [
                f"connect('{self.source_capability}', '{self.target_capability}', "
                f"name='{self.relation}')",
            ]


class PluginGenerator:
    """
    Generates Orion plugin implementations from PluginSpecs.

    Usage:
        generator = PluginGenerator()
        spec = PluginSpec(
            name="search_to_store",
            description="Direct search→store capability",
            source_capability="search",
            target_capability="store",
            relation="requires",
            confidence=0.85,
        )
        code = generator.generate(spec)
        # Returns complete Python code for the plugin
    """

    def generate(self, spec: PluginSpec) -> str:
        """
        Generate a complete Orion plugin from a PluginSpec.

        Args:
            spec: The plugin specification.

        Returns:
            Complete Python code for the plugin.
        """
        provides_list = ", ".join(f'"{p}"' for p in spec.provides)
        requires_list = ", ".join(f'"{r}"' for r in spec.requires)
        events_consumed_list = ", ".join(f'"{e}"' for e in spec.events_consumed)
        events_published_list = ", ".join(f'"{e}"' for e in spec.events_published)

        category_ops = "\n        ".join(
            f"self.category.{op}" for op in spec.category_operations
        )

        plugin_code = textwrap.dedent(f'''\
            # Auto-generated plugin: {spec.name}
            # Generated by KOMPOSOS-IV PluginGenerator
            # Description: {spec.description}
            # Evidence: {spec.evidence}

            from __future__ import annotations

            import logging
            from typing import Any, Dict, List, Optional

            try:
                from orion_core import Plugin
                from orion_core.plugin import on, hook
                HAS_ORION = True
            except ImportError:
                HAS_ORION = False
                class Plugin:
                    def __init__(self, core, **kwargs):
                        self.core = core
                        self.name = kwargs.get('name', 'unknown')
                def on(event):
                    def decorator(fn):
                        return fn
                    return decorator
                def hook(event, priority=10):
                    def decorator(fn):
                        return fn
                    return decorator

            from core.category import Category

            logger = logging.getLogger(__name__)


            class {self._camel_case(spec.name)}Plugin(Plugin):
                """
                {spec.description}

                Auto-generated by KOMPOSOS-IV PluginGenerator.
                Missing primitive detected: {spec.source_capability} → {spec.target_capability}
                Confidence: {spec.confidence:.2f}
                """

                def __init__(self, core, category: Category = None, db_path: str = ":memory:"):
                    super().__init__(
                        core,
                        name="{spec.name}",
                        version="0.1.0",
                        description="{spec.description}",
                        provides=[{provides_list}],
                        requires=[{requires_list}],
                        events_consumed=[{events_consumed_list}],
                        events_published=[{events_published_list}],
                    )

                    self.category = category or Category(db_path=db_path)

                async def on_start(self):
                    """Plugin startup."""
                    logger.info("{spec.name} plugin started")
                    # Establish the missing connection
                    {category_ops}

                async def on_stop(self):
                    """Plugin shutdown."""
                    logger.info("{spec.name} plugin stopped")

                @on({events_consumed_list[0] if spec.events_consumed else '"*"'})
                async def on_{self._snake_case(spec.source_capability)}_output(self, event):
                    """
                    Handle {spec.source_capability} output and route to {spec.target_capability}.
                    """
                    data = event.data
                    logger.debug(
                        f"{spec.name}: routing from {spec.source_capability} "
                        f"to {spec.target_capability}"
                    )

                    # Store the relationship in the category
                    self.category.connect(
                        "{spec.source_capability}",
                        "{spec.target_capability}",
                        name="{spec.relation}",
                        confidence={spec.confidence},
                        metadata={{
                            "source": "auto_generated",
                            "generator": "PluginGenerator",
                            "evidence": {spec.evidence},
                        }},
                    )

                    # Emit completion event
                    await self.emit(
                        "{spec.provides[0] if spec.provides else 'completed'}",
                        {{
                            "source": "{spec.source_capability}",
                            "target": "{spec.target_capability}",
                            "relation": "{spec.relation}",
                            "confidence": {spec.confidence},
                        }},
                    )

                    return data

                async def execute(self, data: Any) -> Any:
                    """
                    Execute the capability: route from {spec.source_capability} to {spec.target_capability}.

                    Args:
                        data: Input data from the source capability.

                    Returns:
                        Data routed to the target capability.
                    """
                    logger.debug(f"{{self.name}}: executing {{data}}")
                    return data
        ''')

        return plugin_code

    def generate_and_save(
        self,
        spec: PluginSpec,
        output_dir: str = "bridges",
    ) -> str:
        """
        Generate a plugin and save it to a file.

        Args:
            spec: The plugin specification.
            output_dir: Directory to save the plugin (default: bridges/).

        Returns:
            Path to the generated file.
        """
        import os
        import pathlib

        code = self.generate(spec)
        filename = f"{self._snake_case(spec.name)}_plugin.py"
        filepath = os.path.join(output_dir, filename)

        pathlib.Path(output_dir).mkdir(parents=True, exist_ok=True)
        with open(filepath, "w") as f:
            f.write(code)

        return filepath

    def verify_plugin(
        self,
        spec: PluginSpec,
        category: "Category" = None,
    ) -> Dict[str, Any]:
        """
        Verify that a generated plugin satisfies its protocol.

        Checks:
        - Provides the declared capabilities
        - Requires the declared dependencies
        - Category operations are valid (source/target exist)
        - Composes with existing plugins (no conflicts)

        Args:
            spec: The plugin specification.
            category: Optional Category for structural verification.

        Returns:
            Dict with verification results.
        """
        results = {
            "spec_valid": True,
            "protocol_valid": True,
            "category_valid": True,
            "composable": True,
            "issues": [],
        }

        # Check spec consistency
        if not spec.name:
            results["spec_valid"] = False
            results["issues"].append("Plugin name is required")
        if not spec.source_capability or not spec.target_capability:
            results["spec_valid"] = False
            results["issues"].append("Source and target capabilities are required")

        # Check category operations
        if category:
            src = category.get(spec.source_capability)
            tgt = category.get(spec.target_capability)

            if not src:
                results["category_valid"] = False
                results["issues"].append(
                    f"Source capability '{spec.source_capability}' not found in Category"
                )
            if not tgt:
                results["category_valid"] = False
                results["issues"].append(
                    f"Target capability '{spec.target_capability}' not found in Category"
                )

            # Check if the edge already exists
            if src and tgt:
                existing = [
                    m for m in category.morphisms()
                    if m.source == spec.source_capability and m.target == spec.target_capability
                ]
                if existing:
                    results["issues"].append(
                        f"Edge {spec.source_capability}→{spec.target_capability} already exists "
                        f"({len(existing)} morphism(s))"
                    )

        # Check composability: does it conflict with existing plugins?
        if category:
            for mor in category.morphisms():
                if (mor.source == spec.source_capability and
                    mor.target == spec.target_capability and
                    mor.name == spec.relation):
                    results["composable"] = False
                    results["issues"].append(
                        f"Conflicts with existing morphism: {mor.id}"
                    )

        return results

    def _camel_case(self, name: str) -> str:
        """Convert snake_case to CamelCase."""
        return "".join(word.capitalize() for word in name.replace("-", "_").split("_"))

    def _snake_case(self, name: str) -> str:
        """Convert to snake_case."""
        return name.replace("-", "_").replace(" ", "_").lower()


class SelfExtensionEngine:
    """
    End-to-end self-extension: detect missing primitive → generate plugin → verify → load.

    This is the system implementing its own architectural corrections.
    """

    def __init__(self, orion_core=None, category: "Category" = None):
        """
        Args:
            orion_core: Orion Core for plugin registration.
            category: The Category for structural verification.
        """
        self.orion = orion_core
        self.category = category
        self.generator = PluginGenerator()
        self._generated_plugins: List[Dict[str, Any]] = []

    async def implement_missing_primitive(
        self,
        source: str,
        target: str,
        relation: str = "requires",
        confidence: float = 0.7,
        evidence: Dict[str, Any] = None,
        auto_load: bool = False,
    ) -> Dict[str, Any]:
        """
        Implement a missing primitive from detection to hot-load.

        Args:
            source: Source capability.
            target: Target capability.
            relation: Relationship type.
            confidence: Confidence that this primitive is missing.
            evidence: Evidence for why this primitive is needed.
            auto_load: If True, hot-load the plugin after generation.

        Returns:
            Dict with generation results and load status.
        """
        # 1. Synthesize PluginSpec
        spec = PluginSpec(
            name=f"{source}_to_{target}",
            description=f"Direct {source}→{target} capability",
            source_capability=source,
            target_capability=target,
            relation=relation,
            confidence=confidence,
            evidence=evidence or {},
        )

        # 2. Generate plugin code
        code = self.generator.generate(spec)

        # 3. Verify
        verification = self.generator.verify_plugin(spec, self.category)

        result = {
            "spec": {
                "name": spec.name,
                "description": spec.description,
                "provides": spec.provides,
                "requires": spec.requires,
            },
            "code_length": len(code),
            "verification": verification,
            "loaded": False,
        }

        # 4. Hot-load if verified and auto_load
        if verification["spec_valid"] and verification["protocol_valid"] and auto_load:
            if self.orion:
                # Execute the generated code and register the plugin
                plugin_module = {}
                exec(compile(code, f"<generated:{spec.name}>", "exec"), plugin_module)

                # Find the plugin class
                plugin_class = None
                for name, obj in plugin_module.items():
                    if name.endswith("Plugin") and isinstance(obj, type):
                        plugin_class = obj
                        break

                if plugin_class:
                    plugin_instance = plugin_class(
                        self.orion,
                        category=self.category,
                    )
                    await self.orion.register_plugin(plugin_instance)
                    result["loaded"] = True
                    result["plugin_name"] = plugin_instance.name

        self._generated_plugins.append(result)
        return result

    def report(self) -> str:
        """Generate a report on self-extension activity."""
        lines = [
            "Self-Extension Report",
            "=" * 50,
            f"Plugins generated: {len(self._generated_plugins)}",
            f"Plugins loaded: {sum(1 for p in self._generated_plugins if p.get('loaded'))}",
            "",
        ]

        for i, plugin in enumerate(self._generated_plugins):
            status = "LOADED" if plugin.get("loaded") else "GENERATED"
            lines.append(
                f"  {i+1}. [{status}] {plugin['spec']['name']}: "
                f"{plugin['spec']['description']}"
            )
            if plugin["verification"]["issues"]:
                for issue in plugin["verification"]["issues"]:
                    lines.append(f"     Issue: {issue}")

        return "\n".join(lines)
